[package]
name = "sapper_query"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]
description = "Query parsing module for sapper web framework."

[dependencies]
url = "*"

sapper = "0.1"
